
name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  js-unit:
    name: JS Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Jest
        run: npm run test:unit

  cypress-e2e:
    name: Cypress E2E
    needs: js-unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start dev server
        run: npm start &

      - name: Wait for server
        run: npx wait-on http://localhost:8080

      - name: Run Cypress integration tests
        run: npm run test:e2e
